### ISSUE TITLE
Bring in ASNH tracking data

### ISSUE THREAD

**Issue by kmkauffm** [kmkauffm/home-or-habitat#3]
Tracking data in ASNH and ASNHZ sheets will be used to filter the start/end times of the GPS data so only capture when the participant was wearing the data. To make sure it matches the rawGPSdata:
- [ ] summarize rawGPSdata  
- [ ] join the 2 dfs  
- [ ] figure out where data is missing or not lining up

**Comment by kmkauffm** [comment]
## not in folder no data and no note
- [x] ASNH090 - device not returned in GPS_downloaded column
- [x] 134_1 - no data on device in GPS_downloaded column
- [x] 134_2 - no data on device in GPS_downloaded column
- [x] z020_2 - GPS_downloaded column says no, no other comment
- [x] z040_2 - GPS_downloaded column says no, no other comment
- [x] z065_1 - didn't know when owner removed device
## in 08Nov folder, start is 01nov
- [x] 116 - according to ASNH sheet the person had this 1nov to 20nov
- [x] 120 - ASNH sheet says person had 1Nov-15Nov, device started recording 9Nov so likely a types in ASNH sheet and person received device on 8Nov
